run:
  timeout: 5m

issues:
  exclude-rules:

    # The tests in cmprefimpl have pass *testing.T values deeply through
    # functions where using t.Helper() doesn't make sense.
    - path: internal/cmprefimpl
      linters:
        - thelper

    - text: "G115.*"
      linters:
        - gosec

    - path: "carto/*"
      linters:
        - asciicheck

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/peterstace/simplefeatures
          - github.com/lib/pq
        deny:
          - pkg: io/ioutil
            desc: Use os or io instead of io/ioutil
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
  errcheck:
    exclude-functions:
      - io.Copy(os.Stdout)
      - (*github.com/peterstace/simplefeatures/rtree.RTree).RangeSearch
      - (*github.com/peterstace/simplefeatures/rtree.RTree).PrioritySearch

# NOTE: every linter supported by golangci-lint is either explicitly included
# or excluded.
linters:

  enable:

    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - intrange
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

  disable:

    # Deprecated by golangci-lint:
    - execinquery

    # The following are disabled because they're not a good match for
    # simplefeatures.
    - cyclop
    - dupl
    - errname
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocyclo
    - godox
    - err113
    - gomnd
    - inamedparam
    - interfacebloat
    - lll
    - maintidx
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - protogetter
    - sloglint
    - testifylint
    - varnamelen
    - wrapcheck
    - wsl
