version: "3.7"
services:
  cmprefimpl:
    build:
      context: .
      dockerfile: geos.Dockerfile
    working_dir: /go/src/github.com/peterstace/simplefeatures
    entrypoint: sh -c "go install ./internal/cmprefimpl/cmpgeos && cmpgeos"
    volumes:
      - ..:/go/src/github.com/peterstace/simplefeatures
    environment:
      - GO111MODULE=on
