version: "2.1"
services:
  geostests:
    build:
      dockerfile: geos.Dockerfile
      args:
        ALPINE_VERSION: $alpine_version
        GEOS_VERSION: $geos_version
    working_dir: /mnt/sf
    entrypoint: go test $tags -test.count=1 -test.run=. ./geos ./internal/rawgeos
    volumes:
      - ..:/mnt/sf
