version: "2.1"
services:
  postgis:
    image: ghcr.io/baosystems/postgis
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "pg_isready -U postgres"
      interval: '100ms'
      timeout: '1s'
      retries: 50
  tests:
    image: golang:1.17
    working_dir: /go/src/github.com/peterstace/simplefeatures
    entrypoint: go test -test.count=1 -test.timeout=30m -test.run=. ./internal/cmprefimpl/cmppg
    volumes:
      - ..:/go/src/github.com/peterstace/simplefeatures
    environment:
      - GO111MODULE=on
    depends_on:
      postgis:
        condition: service_healthy
