version: "2.1"
services:
  geostests:
    build:
      context: .
      dockerfile: geos.Dockerfile
    working_dir: /go/src/github.com/peterstace/simplefeatures
    entrypoint: go test -test.count=1 -test.run=. ./geos
    volumes:
      - .:/go/src/github.com/peterstace/simplefeatures
    environment:
      - GO111MODULE=on
